### ISSUE TITLE
Plugin integration

### ISSUE THREAD

**Issue by iLeafSolutionsPvtLtd** [najeira/flutter-video-player#2]
How do I integrate your plugin in my project?. Can I compile it in pubspec.yaml instead of downloading ?. I want to use this library to show a video slider explaining usage instructions. It doesn't require any play and pause controllers as it should loop infinitely. I recently tried Flutter video player plugin for the purpose. But it worked except one minor issue which i couldn't fix. Video was having different aspect ratio I guess, as a result the frame dint fill the actual space of the video player and a dark line was visible on the right side.And interestingly not all phones had the issue except high quality screen phones like Samsung S8. Any work-around for the issue will be welcomed. I just want to see whether your plugin can help me serve the purpose .Thanks in advance

**Comment by najeira** [comment]
Use https://pub.dev/packages/video_player
